// <auto-generated />
using System;
using ElvaOrderServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElvaOrderServer.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20250708102237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElvaOrderServer.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8b3c7d0-9e1f-4a6b-8c3d-2e5f4a6b8c9d"),
                            CreatedAt = new DateTime(2023, 6, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "John Smith"
                        },
                        new
                        {
                            Id = new Guid("b9c4d8e1-0f2a-5b7c-9d3e-1f6a7b8c9d0e"),
                            CreatedAt = new DateTime(2023, 6, 16, 14, 45, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Emma Johnson"
                        });
                });

            modelBuilder.Entity("ElvaOrderServer.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = new Guid("a8b3c7d0-9e1f-4a6b-8c3d-2e5f4a6b8c9d"),
                            ProductId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = new Guid("a8b3c7d0-9e1f-4a6b-8c3d-2e5f4a6b8c9d"),
                            ProductId = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = new Guid("b9c4d8e1-0f2a-5b7c-9d3e-1f6a7b8c9d0e"),
                            ProductId = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = new Guid("b9c4d8e1-0f2a-5b7c-9d3e-1f6a7b8c9d0e"),
                            ProductId = new Guid("6ba7b810-9dad-11d1-80b4-00c04fd430c8"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ElvaOrderServer.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ElvaOrderServer.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ElvaOrderServer.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
